### ISSUE TITLE
Improve messages for parsing errors

### ISSUE THREAD

**Issue by tadeuzagallo** [tadeuzagallo/verve-lang#24]
Rewriting the parser to better reflect the grammar improved correctness but regressed the state of error messages, e.g.:

For the following program

``` js
foo(a) { a }
```

The compiler would previously give the following error message:

```
Defining function `foo` that is missing type information for arg #1
```

And now, all it tells is:

```
Unexpected token `{` at 1:8
1: foo(a) { a }
          ^
```

**Comment by pscollins** [comment]
Just dropping in off the HN post --- would a parser generator violate your "no dependencies" requirement?

**Comment by tadeuzagallo** [comment]
@pscollins I don't mind it that much... I do miss it when I have to manually keep the grammar in sync with the parser's code tbh, just not enough to start using a generator yet. If I was to do a major change, I'd probably write the type checker in a different language, but again, I plan to make it self hosting at some point.
